### ISSUE TITLE
How to remove namespace completely

### ISSUE THREAD

**Issue by harshzalavadiya** [dtsgenerator/replace-namespace#1]
First of all thank you for creating `dtsgenerator` made my life much easier

Previously i was using `-n ""` for no namespace generation but since now it's recommended to use this plugin how to migrate it use this plugin I tried below config but didn't work as expected

```json
{
  "plugins": {
    "@dtsgenerator/replace-namespace": {
      "map": [
        {
          "from": [true],
          "to": [""]
        }
      ]
    }
  }
}
````

**Comment by horiuchi** [comment]
If you want to remove a nested namespace, you need to add the value(`true` or specific name) to the array for the level you want to remove, as shown below.

```
{
  "plugins": {
    "@dtsgenerator/replace-namespace": {
      "map": [
        {
          "from": [true, true, true],
          "to": []
        }
      ]
    }
  }
}
```
