### ISSUE TITLE
Plugin seems to not work properly

### ISSUE THREAD

**Issue by DamianOsipiuk** [dtsgenerator/replace-namespace#2]
I have successfully used dtsgenerator lib when it was in v2. `namespace` cli option did the trick for me of renaming a top-level namespace.
However, after using v3 with this plugin I cannot make it work properly.
the very beginning of generated file looks like this:
`declare any namespace Definitions {`
And I cannot rename it using this plugin.

Config file that i have tried to use:
```
{
  "plugins": {
    "@dtsgenerator/replace-namespace": {
      "map": [
        {
          "from": ["Definitions"],
          "to": ["MyNameDoestNotWork"]
        }
      ]
    }
  }
}
```
as well as different combinations with `true` and nesting

Any help here?

**Comment by horiuchi** [comment]
First of all, try to make sure that config is recognized correctly with the --info option.

**Comment by DamianOsipiuk** [comment]
Hi,
Yes, I made sure that the config is applied before posting the issue. That is why the other issue to the main lib was posted.

```
Version: 3.1.1
ConfigFile: dtsgen.json

Config:
  input:
    urls: ["https://localhost:9091/openapi.json"]
  outputFile: "./app/typings/api.d.ts"
  target: ESNext
  plugins:
    @dtsgenerator/replace-namespace: {"map":[{"from":["Definitions"],"to":["MyNameDoestNotWork"]}]}

Plugins: count=1
  @dtsgenerator/replace-namespace@1.3.1: replace the namespace names
```

The only change in the generated file is from:
`declare namespace Definitions {`
to
`declare any namespace Definitions {`

**Comment by horiuchi** [comment]
I don't know why any is being added. That's not the way it's supposed to work.
If possible, I would like to see the results without the plugin.

**Comment by DamianOsipiuk** [comment]
Unfortunately it's private project and i cannot share the file.
I will try to provide minimal reproducible example.

**Comment by Menci** [comment]
My result is `declare is namespace Components`.

My schema is on http://demo.syzoj.org/docs-json. The output without the plugin in `Components.Schemas`.

My config is:

```js
  dtsGeneratorConfig.plugins = {
    "@dtsgenerator/replace-namespace": {
      map: [
        {
          from: ["Components", "Schemas"],
          to: ["ApiTypes"]
        }
      ]
    }
  }
```

**Comment by gilleswittenberg** [comment]
We are running into a similar issue in https://github.com/Amsterdam/zaken-frontend/tree/dependabot/npm_and_yarn/typescript-4.0.2. It seems to be caused by an upgrade of TypeScript from 3.x => 4.0 .

config:
```
{
    "plugins": {
        "@dtsgenerator/replace-namespace": {
            "map": [
                {
                    "from": ["Components", "Schemas"],
                    "to": ["API"]
                }
            ]
        }
    }
}
```

result:
`declare is namespace Components {`

**Comment by KostblLb** [comment]
@gilleswittenberg @horiuchi yup, created an angular 10.1 project yestereday which has ts 4, confirm having the same issue

**Comment by crizo23** [comment]
Another confirmation that it's a typescript 4.0 thing. Took me hours to figure out why this plugin worked fine when running with a package.json script, but got the `declare is namespace` with command line - turns out I had a global typescript of 4.0 installed, and 3.x in the local project.

**Comment by Dammic** [comment]
I have the same issue for typescript 4, is there any workaround for this, or a fix coming?
When upgrading from TS 3 to 4, our types were completely changed in terms of namespaces, and I have the same thing with 'declare is namespace Components'

**Comment by henhal** [comment]
Any progress here? This is forcing us to remain on TS3 which is becoming increasingly difficult. I had filed https://github.com/horiuchi/dtsgenerator/issues/453 on the main repo as well.

**Comment by Menci** [comment]
No, you can remain on dtsgenerator 2 which works perfectly fine with TS4.

**Comment by henhal** [comment]
@Menci Yeah I finally decided to step back to dtsgenerator@2, after finding yet another issue making v3 unusable: https://github.com/dtsgenerator/replace-namespace/issues/4
